sudo: true

dist: xenial

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - nvm install --lts
  - nvm use --lts
  - pip install -q tox coverage coveralls tox-travis

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls

cache: pip

notifications:
  email:
    - boerni@gmail.com
